Vagrant.configure("2") do |config|
    config.vm.network "private_network", ip: "192.168.66.3"
    config.vm.box = "puppetlabs/ubuntu-14.04-32-puppet"
    config.vm.provision :shell, path: "bootstrap.sh"
end
