Vagrant.configure("2") do |config|
    config.vm.network "private_network", ip: "192.168.66.2"
    config.vm.box = "ubuntu/trusty64"
    config.vm.provision :shell, path: "bootstrap.sh"
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
    end
end
