Vagrant.configure("2") do |config|
    config.vm.network "private_network", ip: "192.168.66.2"
    config.vm.box = "ubuntu/trusty64"
    config.vm.provision :shell, path: "bootstrap.sh"
    config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
    config.vm.network :forwarded_port, guest: 22, host: 2223, auto_correct: true
    config.ssh.port = 2223
end
